name: protocol-runner

version: 0.0.1
ghc-options:
  # Recommended settings for polysemy
  - -O2
  - -flate-specialise
  - -fspecialise-aggressively
  # - -fplugin=Polysemy.Plugin
  # Useful warnings
  - -Wall
  - -Wcompat
  - -Wredundant-constraints
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns

default-extensions:
  # Recommended extensions for polysemy
  - DataKinds
  - FlexibleContexts
  - GADTs
  - LambdaCase
  - PolyKinds
  - RankNTypes
  - ScopedTypeVariables
  - TypeApplications
  - TypeOperators
  - TypeFamilies
  # - TemplateHaskell

  # Deriving extensions
  - GeneralizedNewtypeDeriving
  - DeriveGeneric

  # Misc extensions
  - OverloadedStrings
  - RecordWildCards

dependencies:
  - base
  - bytestring
  - containers
  - cryptonite
  - memory
  - polysemy
  # - polysemy-plugin
  - stm

library:
 source-dirs:
   - src
 exposed-modules:
   - Effects
   - Effects.Cryptography
   - Effects.CryptoniteInterpreter
   - Effects.Messaging
   - Effects.PrintingEffects
   - Effects.Types
   - Interpreter
   # Generated Code
   - Common
   - Datatypes
   - ExampleProtocols
   - ProtocolExtraction
   - Keys
   - List
   - Logic
   - Maps
   - Messages
   - OrderedType
   - OrderedTypeEx
   - PeanoNat
   - RealWorld
   - Specif

 other-modules: []

executables:

  printProto:
    main: PrintProto.main
    source-dirs: [app]
    dependencies:
      - protocol-runner

# executables:
#   ft:
#     <<: *exedefaults
#     main: FrontendTest.main
#     source-dirs: [frontend, mock]
#   mock-harness:
#     <<: *exedefaults
#     main: QueueMockHarness.main
#     source-dirs: main
#   mock-queue:
#     <<: *exedefaults
#     main: MockQueue.runQueue
#     source-dirs: main
#   psGenerator:
#     <<: *exedefaults
#     main: PSGenerator.main
#     source-dirs: main
